apiVersion: apps/v1
kind: Deployment
metadata:
  name: clodrive-deployment
  namespace: k8s-draft
  labels:
    env: development
spec:   
  template:
    metadata:
      labels:
        env: development
      name: clodrive
    spec:
      containers:
      - name: clodrive
        image: setu3011/clodrive-frontend:latest
        ports:
        - containerPort: 3001
  replicas: 3    
  selector:
    matchLabels:
      env: development