# deployment file for configmap and secret reference

apiVersion: apps/v1
kind: Deployment
metadata:
  name: clodrive-backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: clodrive-backend

  template:
    metadata:
      labels:
        app: clodrive-backend

    spec:
      containers:
        - name: backend
          image: my-backend:latest

          envFrom:
            - configMapRef:
                name: app-config     # Reference to the ConfigMap named 'app-config' to load environment variables from it.

            - secretRef:
                name: app-secret     # Reference to the Secret named 'app-secret' to load sensitive environment variables from it.

          