# Init container that runs to completion and exits before any main application containers are allowed to start

apiVersion: v1
kind: Pod
metadata:
  name: basic-init-pod
  namespace: k8s-draft
spec:
  initContainers:
  - name: my-init-container
    image: busybox
    command: ['echo', 'Init container task completed!']

  containers:
  - name: main-container
    image: nginx
