# Job → runs a task once until it completes successfully

apiVersion: batch/v1
kind: Job
metadata:
  name: backup-job

spec:
  template:
    spec:
      containers:
        - name: backup
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              echo "Starting backup..."
              sleep 10
              echo "Backup completed successfully!"

      restartPolicy: Never

  backoffLimit: 3   # backoffLimit specifies the maximum number of times a Job will retry creating new Pods if the previous Pods fail.
  