#  Pod is the smallest deployable unit in Kubernetes, consisting of one or more tightly coupled containers.

apiVersion: v1
kind: Pod  
metadata:
  name: busybox-pod
  namespace: k8s-draft
  labels:
    env: development
spec:
  initContainers:
  - name: init-container
    image: busybox:latest
    command: ['sh' , '-c', 'echo "Init container started"; sleep 5; echo "Init container completed"']

  containers: 
  - name: main-app
    image: nginx:latest 
    ports:
    - containerPort: 3001


