# bernetes probes are health checks used to monitor containers. A liveness probe determines whether a container needs to be restarted, a readiness probe determines whether a Pod should receive traffic, and a startup probe gives slow-starting applications time to initialize before liveness and readiness checks take over.

# Liveness Probe = Checks if the container is alive or not. If the container is not alive, it will be restarted.

# Readiness Probe = Checks if the container is ready to serve requests and receive traffic. If the container is not ready, it will not receive any traffic.

# Startup Probe = Checks if the container is started or not. If the container is not started, it will be restarted.

apiVersion: apps/v1
kind: Deployment

metadata:
  name: web-app

spec:
  replicas: 3

  selector:
    matchLabels:
      app: web-app

  template:
    metadata:
      labels:
        app: web-app

    spec:
      containers:
        - name: web-app
          image: nginx:latest

          ports:
            - containerPort: 80

          # Startup Probe
          startupProbe:
            httpGet:               # Checks whether your application responds successfully over HTTPS
              path: /
              port: 80
            initialDelaySeconds: 5    # After 5 seconds of starting the container
            periodSeconds: 5        # it will check every 5 seconds
            failureThreshold: 30     # maximum 30 failures the container reports as not started, then it will be restarted

          # Liveness Probe
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3

          # Readiness Probe
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5   # Wait 5 seconds after the container starts before performing the first probe.
            periodSeconds: 5         # Perform the probe every 5 seconds.
            failureThreshold: 3      # Consider the probe failed after 3 consecutive failures.
