apiVersion: v1
kind: Service    
metadata: 
  name: clodrive-nodeport-svc
  namespace: k8s-draft
  labels:
    env: development
spec:
  type: NodePort
  ports:
    - nodePort: 30001
      port: 3001
      targetPort: 3001
  selector:
      env: development
