apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: clodrive-backend-rs
  namespace: clodrive

spec:
  replicas: 3

  selector:
    matchLabels:
      app: clodrive-backend-rs

  template:
    metadata:
      labels:
        app: clodrive-backend-rs

    spec:
      containers:
        - name: backend
          image: setu3011/clodrive-backend:latest

          ports:
            - containerPort: 5000

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"